FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer.py .

ENV BOOTSTRAP_SERVERS=kafka:9092
ENV TOPICS=pg-server.public.users,pg-server.public.orders

CMD ["sh", "-c", "python consumer.py"]
