listeners=http://0.0.0.0:8081
host.name=schema-registry
schema.registry.group.id=schema-registry-standalone
kafkastore.bootstrap.servers=rc1a-6ibie76edoio2ab7.mdb.yandexcloud.net:9091
kafkastore.security.protocol=SASL_SSL
kafkastore.sasl.mechanism=SCRAM-SHA-512
kafkastore.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="registry" password="registry1";
kafkastore.ssl.truststore.type=PEM
kafkastore.ssl.truststore.location=/etc/schema-registry/YandexInternalRootCA.crt
master.eligibility=true
