bootstrap.servers=rc1a-6ibie76edoio2ab7.mdb.yandexcloud.net:9091
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="practicumuser" password="SecurePass2026";
ssl.truststore.type=PEM
ssl.truststore.location=YandexInternalRootCA.crt
