security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
ssl.truststore.password=kafka123
ssl.keystore.location=/etc/kafka/secrets/client.consumer.keystore.jks
ssl.keystore.password=kafka123
ssl.key.password=kafka123

ssl.keystore.type=PKCS12
ssl.truststore.type=PKCS12
